### ISSUE TITLE
Bazooka has the wrong Passive Ability

### ISSUE THREAD

**Issue by RickedySplit** [BSData/modulorka#27]
Bug:
The Bazooka has the "Flamethrowa" Passive Ability.

To Reproduce:
1. Equip a Ladz with the Bazooka
2. Click "View Profiles" on the unit

Expected behavior:
The Bazooka should have the "Anti-Armor" special ability

Info/Context:
 - New Recruit
 - Book Version 36

**Comment by cartag** [comment]
Already fixed, just working on finalizing a big rework in the equipment system. Thanks for the bug report!
